### ISSUE TITLE
Configuring the retention time in Unraid is already possible

### ISSUE THREAD

**Issue by saladm2** [ccmpbll/prometheus-docker#1]
Hey,

I love the idea of your docker - being able to set the retention time in docker using an environmental variable so much simpler! I saw that you posted this as an Unraid Template in their app store and I just wanted to mention that it is currently possible to set the retention time in the already available official prometheus Unraid docker as well.

Unraid has the ability to trigger flags on container startup by setting them in the 'post arguments' section of the docker template. So to set the retention time in the official prometheus Unraid docker, you'd add the following line to the 'post arguments' sections of the docker template:

`--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.retention.time=730d`

This will set the data retention time to 730 days (2 years).

Granted, this took me an actual eternity to figure out and probably isn't well known, but it is possible. Just wanted to let you know!

**Comment by ccmpbll** [comment]
I became aware of this possibility shortly after I created the template. As you mentioned, it wasn't readily obvious that your solution would work, so I went another way. If nothing else, maybe someone else will find this useful. Either way, I had fun creating something. I appreciate the friendly heads up though!

**Comment by yoleska-dev** [comment]
I wasn't sure where to post this in github, but I wanted to say THANK YOU so much for this unraid app.  The primary prometheus app has some buggy features with the /data directory placement and it was driving me nuts.  Yours is perfect.  Thank you Thank you!
