### ISSUE TITLE
Bug in v2.50 of prometheus 

### ISSUE THREAD

**Issue by campbellbartlett** [ccmpbll/prometheus-docker#3]
Hey,

First of all, great name! I don't come across many Campbells.

I have run into [this ](https://github.com/grafana/grafana/issues/82873)issue, so I've opened a [PR ](https://github.com/ccmpbll/prometheus-docker/pull/2)to bump to the latest version of Prometheus.

Let me know if any problems.

Cheers,
Campbell

**Comment by ccmpbll** [comment]
Hello! Works for me, PR has been merged. Thanks!
